clear; close all; clc;

%% Paths and general settings

script_path = mfilename('fullpath');
if isempty(script_path)
    project_dir = pwd;
else
    project_dir = fileparts(script_path);
end

base_dir = fullfile(project_dir, 'Graficos');

scenarios = 1:5;
gain_versions = 1:2;

cycle_duration = 10;
max_cycles_plot = 20;
max_time_plot = max_cycles_plot * cycle_duration;
perturbation_time_start = 0;
max_points_plot = 30000;

show_figures = false;
if show_figures
    figure_visibility = 'on';
else
    figure_visibility = 'off';
end

scenario_folder_names = {
    'Ideal'
    'Ruido'
    'Perturbacao'
    'Variacao_payload'
    'Cond_Inicial'
};

scenario_plot_names = {
    'Ideal scenario'
    'Noise scenario'
    'Torque-disturbance scenario'
    'Payload-variation scenario'
    'Initial-condition scenario'
};

joint_names = {
    '\rho'
    '\theta_1'
    '\theta_2'
};

error_fields = {
    'e_rho'
    'e_the1'
    'e_the2'
};

torque_fields = {
    'u_rho'
    'u_the1'
    'u_the2'
};

colors.trajectory = [0.00 0.00 0.00];
colors.pd = [0.85 0.10 0.10];
colors.ilc = [0.05 0.30 0.85];
colors.perturbation = [0.10 0.45 0.25];

line_width = 1.7;

%% Figure generation

for scenario = scenarios
    if scenario < 1 || scenario > numel(scenario_folder_names)
        warning('Invalid scenario %d. The scenario was skipped.', scenario);
        continue;
    end

    scenario_folder = sprintf( ...
        '%d_%s', ...
        scenario, ...
        scenario_folder_names{scenario});

    scenario_output_dir = fullfile(base_dir, scenario_folder);
    if ~exist(scenario_output_dir, 'dir')
        mkdir(scenario_output_dir);
    end

    % Perturbations are identical for all gains and control methods.
    if scenario ~= 1
        perturbation_file = findFirstAvailablePDFile( ...
            base_dir, scenario, gain_versions);

        if isempty(perturbation_file)
            warning( ...
                'No PD data file was found for scenario %d. ', ...
                'The perturbation figure was skipped.', ...
                scenario);
        else
            perturbation_data = load(perturbation_file);

            savePerturbationFigure( ...
                perturbation_data, ...
                scenario, ...
                scenario_output_dir, ...
                figure_visibility, ...
                perturbation_time_start, ...
                max_time_plot, ...
                max_points_plot, ...
                joint_names, ...
                scenario_plot_names{scenario}, ...
                colors);
        end
    end

    for gain_version = gain_versions
        pd_file = fullfile( ...
            base_dir, ...
            sprintf( ...
                'PD_Dados_Cenario_%d_Gains_%d.mat', ...
                scenario, ...
                gain_version));

        ilc_file = fullfile( ...
            base_dir, ...
            sprintf( ...
                'ILC_Dados_Cenario_%d_Gains_%d.mat', ...
                scenario, ...
                gain_version));

        if ~isfile(pd_file)
            warning('File not found: %s', pd_file);
            continue;
        end

        if ~isfile(ilc_file)
            warning('File not found: %s', ilc_file);
            continue;
        end

        pd_data = load(pd_file);
        ilc_data = load(ilc_file);

        gain_output_dir = fullfile( ...
            scenario_output_dir, ...
            sprintf('Gain_%d', gain_version));

        if ~exist(gain_output_dir, 'dir')
            mkdir(gain_output_dir);
        end

        time_start = 0;

        file_prefix = sprintf( ...
            'Scenario_%02d_Gain_%02d', ...
            scenario, ...
            gain_version);

        savePositionFigure( ...
            pd_data, ...
            ilc_data, ...
            scenario_plot_names{scenario}, ...
            gain_version, ...
            joint_names, ...
            gain_output_dir, ...
            file_prefix, ...
            figure_visibility, ...
            time_start, ...
            max_time_plot, ...
            max_points_plot, ...
            colors, ...
            line_width);

        saveTimeSeriesFigure( ...
            pd_data, ...
            ilc_data, ...
            torque_fields, ...
            scenario_plot_names{scenario}, ...
            gain_version, ...
            joint_names, ...
            'Joint Torques over Time', ...
            'Torque', ...
            'Torque (N\cdot m)', ...
            'Torque_Over_Time', ...
            gain_output_dir, ...
            file_prefix, ...
            figure_visibility, ...
            time_start, ...
            max_time_plot, ...
            max_points_plot, ...
            colors, ...
            line_width);

        saveTimeSeriesFigure( ...
            pd_data, ...
            ilc_data, ...
            error_fields, ...
            scenario_plot_names{scenario}, ...
            gain_version, ...
            joint_names, ...
            'Joint Errors over Time', ...
            'Error', ...
            'Error (deg)', ...
            'Error_Over_Time', ...
            gain_output_dir, ...
            file_prefix, ...
            figure_visibility, ...
            time_start, ...
            max_time_plot, ...
            max_points_plot, ...
            colors, ...
            line_width);

        saveMetricsFigure( ...
            pd_data, ...
            ilc_data, ...
            scenario_plot_names{scenario}, ...
            gain_version, ...
            joint_names, ...
            gain_output_dir, ...
            file_prefix, ...
            figure_visibility, ...
            max_cycles_plot, ...
            colors, ...
            line_width);
    end
end

disp('Plot generation code completed.');

%% Local functions

function savePositionFigure( ...
    pd_data, ...
    ilc_data, ...
    scenario_name, ...
    gain_version, ...
    joint_names, ...
    output_dir, ...
    file_prefix, ...
    visibility, ...
    time_start, ...
    requested_time_end, ...
    max_points, ...
    colors, ...
    line_width)

    if ~isfield(pd_data, 'juntas') || ~isfield(ilc_data, 'juntas')
        warning( ...
            ['The variable juntas was not found in both controller ', ...
             'files. The position figure was skipped.']);
        return;
    end

    [time_pd, joints_pd] = getMultichannelSignal(pd_data.juntas);
    [time_ilc, joints_ilc] = getMultichannelSignal(ilc_data.juntas);

    if size(joints_pd, 2) < 6 || size(joints_ilc, 2) < 6
        warning( ...
            ['The variable juntas must contain at least six channels: ', ...
             '[ref_0, pos_0, ref_1, pos_1, ref_2, pos_2]. ', ...
             'The position figure was skipped.']);
        return;
    end

    time_end = min([requested_time_end, time_pd(end), time_ilc(end)]);
    time_start_plot = max([time_start, time_pd(1), time_ilc(1)]);

    if time_end <= time_start_plot
        warning('No position data are available in the requested interval.');
        return;
    end

    fig = createFigure( ...
        sprintf('%s - Gain %d - Joint Positions', scenario_name, gain_version), ...
        visibility, ...
        [50 50 1450 980]);

    layout = tiledlayout( ...
        fig, ...
        3, ...
        1, ...
        'TileSpacing', 'compact', ...
        'Padding', 'compact');

    reference_columns = [1 3 5];
    position_columns = [2 4 6];

    for joint = 1:3
        ax = nexttile(layout);
        hold(ax, 'on');

        [reference_time, reference_position] = cropAndReduceSignal( ...
            time_pd, ...
            joints_pd(:, reference_columns(joint)), ...
            time_start_plot, ...
            time_end, ...
            max_points);

        [pd_time, pd_position] = cropAndReduceSignal( ...
            time_pd, ...
            joints_pd(:, position_columns(joint)), ...
            time_start_plot, ...
            time_end, ...
            max_points);

        [ilc_time, ilc_position] = cropAndReduceSignal( ...
            time_ilc, ...
            joints_ilc(:, position_columns(joint)), ...
            time_start_plot, ...
            time_end, ...
            max_points);

        trajectory_line = plot( ...
            ax, ...
            reference_time, ...
            reference_position, ...
            '--', ...
            'Color', colors.trajectory, ...
            'LineWidth', 1.5);

        pd_line = plot( ...
            ax, ...
            pd_time, ...
            pd_position, ...
            '-', ...
            'Color', colors.pd, ...
            'LineWidth', line_width);

        ilc_line = plot( ...
            ax, ...
            ilc_time, ...
            ilc_position, ...
            '-', ...
            'Color', colors.ilc, ...
            'LineWidth', line_width);

        configureTimeAxis( ...
            ax, ...
            time_start_plot, ...
            time_end, ...
            sprintf('Joint %s Position over Time', joint_names{joint}), ...
            'Position (deg)');

        if joint == 1
            addBoldLegend( ...
                ax, ...
                [trajectory_line, pd_line, ilc_line], ...
                {'Trajectory', 'PD', 'PD + ILC'});
        end
    end

    title( ...
        layout, ...
        sprintf('%s - Gain %d - Joint Positions over Time', ...
            scenario_name, gain_version), ...
        'FontName', 'Times New Roman', ...
        'FontSize', 17, ...
        'FontWeight', 'bold', ...
        'Interpreter', 'tex');

    applyFigureFont(fig);
    exportFigure( ...
        fig, ...
        fullfile(output_dir, [file_prefix '_Position_Over_Time.png']), ...
        visibility);
end

function saveTimeSeriesFigure( ...
    pd_data, ...
    ilc_data, ...
    signal_fields, ...
    scenario_name, ...
    gain_version, ...
    joint_names, ...
    overall_title, ...
    signal_name, ...
    y_label, ...
    file_suffix, ...
    output_dir, ...
    file_prefix, ...
    visibility, ...
    time_start, ...
    requested_time_end, ...
    max_points, ...
    colors, ...
    line_width)

    number_of_joints = numel(signal_fields);
    time_pd = cell(number_of_joints, 1);
    signal_pd = cell(number_of_joints, 1);
    time_ilc = cell(number_of_joints, 1);
    signal_ilc = cell(number_of_joints, 1);

    for joint = 1:number_of_joints
        field_name = signal_fields{joint};

        if ~isfield(pd_data, field_name) || ~isfield(ilc_data, field_name)
            warning( ...
                'The field %s was not found for both controllers.', ...
                field_name);
            return;
        end

        [time_pd{joint}, signal_pd{joint}] = getSingleSignal( ...
            pd_data.(field_name));

        [time_ilc{joint}, signal_ilc{joint}] = getSingleSignal( ...
            ilc_data.(field_name));
    end

    first_times = zeros(2 * number_of_joints, 1);
    final_times = zeros(2 * number_of_joints, 1);

    for joint = 1:number_of_joints
        first_times(2 * joint - 1) = time_pd{joint}(1);
        first_times(2 * joint) = time_ilc{joint}(1);
        final_times(2 * joint - 1) = time_pd{joint}(end);
        final_times(2 * joint) = time_ilc{joint}(end);
    end

    time_start_plot = max([time_start; first_times]);
    time_end = min([requested_time_end; final_times]);

    if time_end <= time_start_plot
        warning('No %s data are available in the requested interval.', signal_name);
        return;
    end

    fig = createFigure( ...
        sprintf('%s - Gain %d - %s', ...
            scenario_name, gain_version, overall_title), ...
        visibility, ...
        [60 60 1450 980]);

    layout = tiledlayout( ...
        fig, ...
        3, ...
        1, ...
        'TileSpacing', 'compact', ...
        'Padding', 'compact');

    for joint = 1:number_of_joints
        ax = nexttile(layout);
        hold(ax, 'on');

        [pd_time_plot, pd_signal_plot] = cropAndReduceSignal( ...
            time_pd{joint}, ...
            signal_pd{joint}, ...
            time_start_plot, ...
            time_end, ...
            max_points);

        [ilc_time_plot, ilc_signal_plot] = cropAndReduceSignal( ...
            time_ilc{joint}, ...
            signal_ilc{joint}, ...
            time_start_plot, ...
            time_end, ...
            max_points);

        pd_line = plot( ...
            ax, ...
            pd_time_plot, ...
            pd_signal_plot, ...
            '-', ...
            'Color', colors.pd, ...
            'LineWidth', line_width);

        ilc_line = plot( ...
            ax, ...
            ilc_time_plot, ...
            ilc_signal_plot, ...
            '-', ...
            'Color', colors.ilc, ...
            'LineWidth', line_width);

        configureTimeAxis( ...
            ax, ...
            time_start_plot, ...
            time_end, ...
            sprintf('Joint %s %s over Time', ...
                joint_names{joint}, signal_name), ...
            y_label);

        if joint == 1
            addBoldLegend(ax, [pd_line, ilc_line], {'PD', 'PD + ILC'});
        end
    end

    title( ...
        layout, ...
        sprintf('%s - Gain %d - %s', ...
            scenario_name, gain_version, overall_title), ...
        'FontName', 'Times New Roman', ...
        'FontSize', 17, ...
        'FontWeight', 'bold', ...
        'Interpreter', 'tex');

    applyFigureFont(fig);
    exportFigure( ...
        fig, ...
        fullfile(output_dir, [file_prefix '_' file_suffix '.png']), ...
        visibility);
end

function saveMetricsFigure( ...
    pd_data, ...
    ilc_data, ...
    scenario_name, ...
    gain_version, ...
    joint_names, ...
    output_dir, ...
    file_prefix, ...
    visibility, ...
    max_cycles, ...
    colors, ...
    line_width)

    metric_fields = {
        'metric_RMSE'
        'metric_MEPI'
        'metric_ISE'
    };

    metric_titles = {
        'RMSE per Cycle'
        'Maximum Error per Cycle'
        'Integral of Squared Error per Cycle'
    };

    metric_labels = {
        'RMSE (deg)'
        'Maximum error (deg)'
        'ISE (deg^2\cdot s)'
    };

    metric_pd = cell(3, 3);
    metric_ilc = cell(3, 3);
    available_cycles = max_cycles;

    for metric = 1:3
        field_name = metric_fields{metric};

        if ~isfield(pd_data, field_name) || ~isfield(ilc_data, field_name)
            warning( ...
                'The metric field %s was not found for both controllers.', ...
                field_name);
            return;
        end

        for joint = 1:3
            metric_pd{metric, joint} = getMetricColumn( ...
                pd_data.(field_name), joint);

            metric_ilc{metric, joint} = getMetricColumn( ...
                ilc_data.(field_name), joint);

            available_cycles = min([ ...
                available_cycles, ...
                numel(metric_pd{metric, joint}), ...
                numel(metric_ilc{metric, joint})]);
        end
    end

    if available_cycles < 1
        warning('No metric cycles are available for plotting.');
        return;
    end

    cycles = 1:available_cycles;

    fig = createFigure( ...
        sprintf('%s - Gain %d - Metrics per Cycle', ...
            scenario_name, gain_version), ...
        visibility, ...
        [40 40 1750 1080]);

    layout = tiledlayout( ...
        fig, ...
        3, ...
        3, ...
        'TileSpacing', 'compact', ...
        'Padding', 'compact');

    for metric = 1:3
        for joint = 1:3
            ax = nexttile(layout);
            hold(ax, 'on');

            pd_line = plot( ...
                ax, ...
                cycles, ...
                metric_pd{metric, joint}(1:available_cycles), ...
                '-o', ...
                'Color', colors.pd, ...
                'MarkerFaceColor', colors.pd, ...
                'MarkerEdgeColor', colors.pd, ...
                'MarkerSize', 5, ...
                'LineWidth', line_width);

            ilc_line = plot( ...
                ax, ...
                cycles, ...
                metric_ilc{metric, joint}(1:available_cycles), ...
                '-^', ...
                'Color', colors.ilc, ...
                'MarkerFaceColor', colors.ilc, ...
                'MarkerEdgeColor', colors.ilc, ...
                'MarkerSize', 5.5, ...
                'LineWidth', line_width);

            configureMetricAxis( ...
                ax, ...
                available_cycles, ...
                sprintf('Joint %s - %s', ...
                    joint_names{joint}, metric_titles{metric}), ...
                metric_labels{metric});

            if metric == 1 && joint == 1
                addBoldLegend( ...
                    ax, ...
                    [pd_line, ilc_line], ...
                    {'PD', 'PD + ILC'});
            end
        end
    end

    title( ...
        layout, ...
        sprintf('%s - Gain %d - Performance Metrics per Cycle', ...
            scenario_name, gain_version), ...
        'FontName', 'Times New Roman', ...
        'FontSize', 18, ...
        'FontWeight', 'bold', ...
        'Interpreter', 'tex');

    applyFigureFont(fig);
    exportFigure( ...
        fig, ...
        fullfile(output_dir, [file_prefix '_Metrics_Per_Cycle.png']), ...
        visibility);
end

function savePerturbationFigure( ...
    data, ...
    scenario, ...
    output_dir, ...
    visibility, ...
    time_start, ...
    requested_time_end, ...
    max_points, ...
    joint_names, ...
    scenario_name, ...
    colors)

    switch scenario
        case 2
            saveNoiseFigure( ...
                data, ...
                output_dir, ...
                visibility, ...
                time_start, ...
                requested_time_end, ...
                max_points, ...
                joint_names, ...
                scenario_name, ...
                colors);

        case 3
            saveTorqueDisturbanceFigure( ...
                data, ...
                output_dir, ...
                visibility, ...
                time_start, ...
                requested_time_end, ...
                max_points, ...
                joint_names, ...
                scenario_name, ...
                colors);

        case 4
            savePayloadFigure( ...
                data, ...
                output_dir, ...
                visibility, ...
                time_start, ...
                requested_time_end, ...
                max_points, ...
                scenario_name, ...
                colors);

        case 5
            saveInitialConditionFigure( ...
                data, ...
                output_dir, ...
                visibility, ...
                time_start, ...
                requested_time_end, ...
                max_points, ...
                joint_names, ...
                scenario_name, ...
                colors);
    end
end

function saveNoiseFigure( ...
    data, ...
    output_dir, ...
    visibility, ...
    time_start, ...
    requested_time_end, ...
    max_points, ...
    joint_names, ...
    scenario_name, ...
    colors)

    if ~isfield(data, 'noises')
        warning('The variable noises was not found.');
        return;
    end

    [time, noise] = getMultichannelSignal(data.noises);
    if size(noise, 2) < 6
        warning('The variable noises must contain six channels.');
        return;
    end

    time_start_plot = max(time_start, time(1));
    time_end = min(requested_time_end, time(end));
    if time_end <= time_start_plot
        warning('No noise data are available in the requested interval.');
        return;
    end

    fig = createFigure( ...
        sprintf('%s - Injected Noise', scenario_name), ...
        visibility, ...
        [50 50 1550 1000]);

    layout = tiledlayout( ...
        fig, ...
        3, ...
        2, ...
        'TileSpacing', 'compact', ...
        'Padding', 'compact');

    for joint = 1:3
        for signal_type = 1:2
            channel = 2 * (joint - 1) + signal_type;
            ax = nexttile(layout);

            [time_plot, noise_plot] = cropAndReduceSignal( ...
                time, ...
                noise(:, channel), ...
                time_start_plot, ...
                time_end, ...
                max_points);

            plot( ...
                ax, ...
                time_plot, ...
                noise_plot, ...
                '-', ...
                'Color', colors.perturbation, ...
                'LineWidth', 1.25);

            if signal_type == 1
                signal_title = 'Position Noise over Time';
                y_label = 'Noise (deg)';
            else
                signal_title = 'Angular-Velocity Noise over Time';
                y_label = 'Noise (rad/s)';
            end

            configureTimeAxis( ...
                ax, ...
                time_start_plot, ...
                time_end, ...
                sprintf('Joint %s - %s', ...
                    joint_names{joint}, signal_title), ...
                y_label);
        end
    end

    title( ...
        layout, ...
        sprintf('%s - Injected Noise over Time', scenario_name), ...
        'FontName', 'Times New Roman', ...
        'FontSize', 17, ...
        'FontWeight', 'bold', ...
        'Interpreter', 'tex');

    applyFigureFont(fig);
    exportFigure( ...
        fig, ...
        fullfile(output_dir, 'Scenario_02_Injected_Noise.png'), ...
        visibility);
end

function saveTorqueDisturbanceFigure( ...
    data, ...
    output_dir, ...
    visibility, ...
    time_start, ...
    requested_time_end, ...
    max_points, ...
    joint_names, ...
    scenario_name, ...
    colors)

    if ~isfield(data, 'disturbances')
        warning('The variable disturbances was not found.');
        return;
    end

    [time, disturbance] = getMultichannelSignal(data.disturbances);
    if size(disturbance, 2) < 3
        warning('The variable disturbances must contain three channels.');
        return;
    end

    time_start_plot = max(time_start, time(1));
    time_end = min(requested_time_end, time(end));
    if time_end <= time_start_plot
        warning( ...
            'No torque-disturbance data are available in the requested interval.');
        return;
    end

    fig = createFigure( ...
        sprintf('%s - Injected Torque Disturbance', scenario_name), ...
        visibility, ...
        [60 60 1450 980]);

    layout = tiledlayout( ...
        fig, ...
        3, ...
        1, ...
        'TileSpacing', 'compact', ...
        'Padding', 'compact');

    for joint = 1:3
        ax = nexttile(layout);

        [time_plot, disturbance_plot] = cropAndReduceSignal( ...
            time, ...
            disturbance(:, joint), ...
            time_start_plot, ...
            time_end, ...
            max_points);

        plot( ...
            ax, ...
            time_plot, ...
            disturbance_plot, ...
            '-', ...
            'Color', colors.perturbation, ...
            'LineWidth', 1.7);

        configureTimeAxis( ...
            ax, ...
            time_start_plot, ...
            time_end, ...
            sprintf('Joint %s Torque Disturbance over Time', ...
                joint_names{joint}), ...
            'Disturbance torque (N\cdot m)');
    end

    title( ...
        layout, ...
        sprintf('%s - Injected Torque Disturbance over Time', scenario_name), ...
        'FontName', 'Times New Roman', ...
        'FontSize', 17, ...
        'FontWeight', 'bold', ...
        'Interpreter', 'tex');

    applyFigureFont(fig);
    exportFigure( ...
        fig, ...
        fullfile(output_dir, 'Scenario_03_Torque_Disturbance.png'), ...
        visibility);
end

function savePayloadFigure( ...
    data, ...
    output_dir, ...
    visibility, ...
    time_start, ...
    requested_time_end, ...
    max_points, ...
    scenario_name, ...
    colors)

    if ~isfield(data, 'm3')
        warning('The variable m3 was not found.');
        return;
    end

    [time, mass] = getSingleSignal(data.m3);
    time_start_plot = max(time_start, time(1));
    time_end = min(requested_time_end, time(end));

    if time_end <= time_start_plot
        warning('No payload data are available in the requested interval.');
        return;
    end

    [time_plot, mass_plot] = cropAndReduceSignal( ...
        time, ...
        mass, ...
        time_start_plot, ...
        time_end, ...
        max_points);

    fig = createFigure( ...
        sprintf('%s - Payload Variation', scenario_name), ...
        visibility, ...
        [100 100 1350 720]);

    ax = axes('Parent', fig);
    plot( ...
        ax, ...
        time_plot, ...
        mass_plot, ...
        '-', ...
        'Color', colors.perturbation, ...
        'LineWidth', 1.9);

    configureTimeAxis( ...
        ax, ...
        time_start_plot, ...
        time_end, ...
        'Link Mass m_3 over Time', ...
        'm_3 (kg)');

    title( ...
        ax, ...
        sprintf('%s - Payload Variation over Time', scenario_name), ...
        'FontName', 'Times New Roman', ...
        'FontSize', 17, ...
        'FontWeight', 'bold', ...
        'Interpreter', 'tex');

    applyFigureFont(fig);
    exportFigure( ...
        fig, ...
        fullfile(output_dir, 'Scenario_04_Payload_Variation.png'), ...
        visibility);
end

function saveInitialConditionFigure( ...
    data, ...
    output_dir, ...
    visibility, ...
    time_start, ...
    requested_time_end, ...
    max_points, ...
    joint_names, ...
    scenario_name, ...
    colors)

    if ~isfield(data, 'error_initialCondition')
        warning('The variable error_initialCondition was not found.');
        return;
    end

    [time, initial_error] = getMultichannelSignal( ...
        data.error_initialCondition);

    if size(initial_error, 2) < 5
        warning( ...
            ['The variable error_initialCondition must contain the ', ...
             'three angular-error channels.']);
        return;
    end

    time_start_plot = max(time_start, time(1));
    time_end = min(requested_time_end, time(end));
    if time_end <= time_start_plot
        warning( ...
            'No initial-condition-error data are available in the requested interval.');
        return;
    end

    angular_channels = [1 3 5];

    fig = createFigure( ...
        sprintf('%s - Initial-Condition Errors', scenario_name), ...
        visibility, ...
        [60 60 1450 980]);

    layout = tiledlayout( ...
        fig, ...
        3, ...
        1, ...
        'TileSpacing', 'compact', ...
        'Padding', 'compact');

    for joint = 1:3
        ax = nexttile(layout);

        [time_plot, error_plot] = cropAndReduceSignal( ...
            time, ...
            initial_error(:, angular_channels(joint)), ...
            time_start_plot, ...
            time_end, ...
            max_points);

        plot( ...
            ax, ...
            time_plot, ...
            error_plot, ...
            '-', ...
            'Color', colors.perturbation, ...
            'LineWidth', 1.7);

        configureTimeAxis( ...
            ax, ...
            time_start_plot, ...
            time_end, ...
            sprintf('Joint %s Initial-Condition Error over Time', ...
                joint_names{joint}), ...
            'Injected error (deg)');
    end

    title( ...
        layout, ...
        sprintf('%s - Injected Initial-Condition Errors over Time', ...
            scenario_name), ...
        'FontName', 'Times New Roman', ...
        'FontSize', 17, ...
        'FontWeight', 'bold', ...
        'Interpreter', 'tex');

    applyFigureFont(fig);
    exportFigure( ...
        fig, ...
        fullfile(output_dir, 'Scenario_05_Initial_Condition_Error.png'), ...
        visibility);
end

function file_path = findFirstAvailablePDFile(base_dir, scenario, gain_versions)
    file_path = '';

    for gain_version = gain_versions
        candidate = fullfile( ...
            base_dir, ...
            sprintf( ...
                'PD_Dados_Cenario_%d_Gains_%d.mat', ...
                scenario, ...
                gain_version));

        if isfile(candidate)
            file_path = candidate;
            return;
        end
    end
end

function fig = createFigure(figure_name, visibility, position)
    fig = figure( ...
        'Name', figure_name, ...
        'Visible', visibility, ...
        'Color', 'w', ...
        'Position', position);
end

function configureTimeAxis(ax, time_start, time_end, plot_title, y_label)
    grid(ax, 'on');
    box(ax, 'on');
    xlim(ax, [time_start, time_end]);

    % Align the x-axis markers with the beginning of each 10-second cycle.
    cycle_duration = 10;
    first_cycle_tick = ceil(time_start / cycle_duration) * cycle_duration;
    last_cycle_tick = floor(time_end / cycle_duration) * cycle_duration;

    if first_cycle_tick <= last_cycle_tick
        xticks(ax, first_cycle_tick:cycle_duration:last_cycle_tick);
    end

    title( ...
        ax, ...
        plot_title, ...
        'FontName', 'Times New Roman', ...
        'FontSize', 14, ...
        'FontWeight', 'bold', ...
        'Interpreter', 'tex');

    xlabel( ...
        ax, ...
        'Time (s)', ...
        'FontName', 'Times New Roman', ...
        'FontSize', 13, ...
        'FontWeight', 'bold');

    ylabel( ...
        ax, ...
        y_label, ...
        'FontName', 'Times New Roman', ...
        'FontSize', 13, ...
        'FontWeight', 'bold', ...
        'Interpreter', 'tex');

    ax.FontName = 'Times New Roman';
    ax.FontSize = 12;
    ax.FontWeight = 'bold';
    ax.LineWidth = 1.0;
end

function configureMetricAxis(ax, number_of_cycles, plot_title, y_label)
    grid(ax, 'on');
    box(ax, 'on');

    if number_of_cycles == 1
        xlim(ax, [0.5 1.5]);
        xticks(ax, 1);
    else
        xlim(ax, [1 number_of_cycles]);
        xticks(ax, 1:number_of_cycles);
    end

    title( ...
        ax, ...
        plot_title, ...
        'FontName', 'Times New Roman', ...
        'FontSize', 12, ...
        'FontWeight', 'bold', ...
        'Interpreter', 'tex');

    xlabel( ...
        ax, ...
        'Cycle', ...
        'FontName', 'Times New Roman', ...
        'FontSize', 11, ...
        'FontWeight', 'bold');

    ylabel( ...
        ax, ...
        y_label, ...
        'FontName', 'Times New Roman', ...
        'FontSize', 11, ...
        'FontWeight', 'bold', ...
        'Interpreter', 'tex');

    ax.FontName = 'Times New Roman';
    ax.FontSize = 10.5;
    ax.FontWeight = 'bold';
    ax.LineWidth = 1.0;
end

function addBoldLegend(ax, lines, labels)
    legend( ...
        ax, ...
        lines, ...
        labels, ...
        'Location', 'northeast', ...
        'FontName', 'Times New Roman', ...
        'FontSize', 11, ...
        'FontWeight', 'bold', ...
        'Interpreter', 'tex');
end

function applyFigureFont(fig)
    set( ...
        findall(fig, '-property', 'FontName'), ...
        'FontName', 'Times New Roman');

    set( ...
        findall(fig, 'Type', 'axes'), ...
        'FontWeight', 'bold');
end

function exportFigure(fig, file_path, visibility)
    exportgraphics(fig, file_path, 'Resolution', 300);

    if strcmpi(visibility, 'off')
        close(fig);
    end
end

function values = getMetricColumn(metric_data, joint)
    values = squeeze(metric_data);

    if ~ismatrix(values)
        error('Metric data must be a two-dimensional array.');
    end

    if size(values, 1) > 3 && size(values, 2) >= joint
        values = values(:, joint);
    elseif size(values, 1) >= joint
        values = values(joint, :).';
    else
        error('Metric data do not contain joint %d.', joint);
    end

    values = values(:);
    values = values(isfinite(values));
end

function [time, data] = getSingleSignal(signal)
    [time, data] = getMultichannelSignal(signal);

    if size(data, 2) > 1
        data = data(:, 1);
    end

    data = data(:);
end

function [time, data] = getMultichannelSignal(signal)
    if isa(signal, 'timeseries')
        time = signal.Time;
        data = signal.Data;
    elseif isstruct(signal) && ...
            isfield(signal, 'Time') && ...
            isfield(signal, 'Data')
        time = signal.Time;
        data = signal.Data;
    else
        error( ...
            ['Signal data must be a timeseries or a structure ', ...
             'containing Time and Data fields.']);
    end

    time = time(:);
    data = squeeze(data);

    if isvector(data)
        data = data(:);
    end

    if size(data, 1) ~= numel(time) && size(data, 2) == numel(time)
        data = data.';
    end

    number_of_samples = min(numel(time), size(data, 1));
    time = time(1:number_of_samples);
    data = data(1:number_of_samples, :);

    valid_samples = isfinite(time) & all(isfinite(data), 2);
    time = time(valid_samples);
    data = data(valid_samples, :);

    [time, unique_indices] = unique(time, 'stable');
    data = data(unique_indices, :);

    if isempty(time)
        error('Signal data contain no valid samples.');
    end
end

function [time_plot, signal_plot] = cropAndReduceSignal( ...
    time, ...
    signal, ...
    time_start, ...
    time_end, ...
    max_points)

    mask = time >= time_start & time <= time_end;
    time_plot = time(mask);
    signal_plot = signal(mask);

    if isempty(time_plot)
        return;
    end

    number_of_points = numel(time_plot);
    if number_of_points > max_points
        indices = unique(round(linspace(1, number_of_points, max_points)));
        time_plot = time_plot(indices);
        signal_plot = signal_plot(indices);
    end
end
