clear; close all; clc;

%% Paths and settings

script_path = mfilename('fullpath');
if isempty(script_path)
    project_dir = pwd;
else
    project_dir = fileparts(script_path);
end

graphics_dir = fullfile(project_dir, 'Graficos');

cycle_duration = 10;
shift_time = cycle_duration / 2;
Ts = 0.01;
show_figure = true;

joint_names = {
    '\rho'
    '\theta_1'
    '\theta_2'
};

joint_colors = [
    0.10 0.45 0.25
    0.85 0.10 0.10
    0.05 0.30 0.85
];

%% Generate the same trajectories used by main_automacao.m

addpath(project_dir);

t_pick = 0:Ts:cycle_duration/2-Ts;
t_return = 0:Ts:cycle_duration/2-Ts;

[q0_pick, qd0_pick, qdd0_pick] = trajetoria(0, 120, t_pick);
[q1_pick, qd1_pick, qdd1_pick] = trajetoria(0, -90, t_pick);
[q2_pick, qd2_pick, qdd2_pick] = trajetoria(0, 90, t_pick);

[q0_return, qd0_return, qdd0_return] = trajetoria( ...
    120, -120, t_return);
[q1_return, qd1_return, qdd1_return] = trajetoria( ...
    -90, 90, t_return);
[q2_return, qd2_return, qdd2_return] = trajetoria( ...
    90, -90, t_return);

cycle_time = [
    q0_pick(:, 1)
    q0_return(:, 1) + shift_time
];

reference_position = [
    [q0_pick(:, 2); q0_return(:, 2)], ...
    [q1_pick(:, 2); q1_return(:, 2)], ...
    [q2_pick(:, 2); q2_return(:, 2)]
];

reference_velocity = deg2rad([
    [qd0_pick(:, 2); qd0_return(:, 2)], ...
    [qd1_pick(:, 2); qd1_return(:, 2)], ...
    [qd2_pick(:, 2); qd2_return(:, 2)]
]);

reference_acceleration = deg2rad([
    [qdd0_pick(:, 2); qdd0_return(:, 2)], ...
    [qdd1_pick(:, 2); qdd1_return(:, 2)], ...
    [qdd2_pick(:, 2); qdd2_return(:, 2)]
]);

%% Plot one trajectory cycle

if show_figure
    visibility = 'on';
else
    visibility = 'off';
end

plotTrajectoryQuantity( ...
    cycle_time, ...
    reference_position, ...
    cycle_duration, ...
    joint_names, ...
    joint_colors, ...
    visibility, ...
    graphics_dir, ...
    'Position', ...
    'Position (deg)', ...
    'Reference Joint Positions - One Cycle', ...
    'Reference_Joint_Positions_One_Cycle.png');

plotTrajectoryQuantity( ...
    cycle_time, ...
    reference_velocity, ...
    cycle_duration, ...
    joint_names, ...
    joint_colors, ...
    visibility, ...
    graphics_dir, ...
    'Angular Velocity', ...
    'Angular velocity (rad/s)', ...
    'Reference Joint Angular Velocities - One Cycle', ...
    'Reference_Joint_Velocities_One_Cycle.png');

plotTrajectoryQuantity( ...
    cycle_time, ...
    reference_acceleration, ...
    cycle_duration, ...
    joint_names, ...
    joint_colors, ...
    visibility, ...
    graphics_dir, ...
    'Angular Acceleration', ...
    'Angular acceleration (rad/s^2)', ...
    'Reference Joint Angular Accelerations - One Cycle', ...
    'Reference_Joint_Accelerations_One_Cycle.png');

%% Local functions

function plotTrajectoryQuantity( ...
    time, ...
    values, ...
    cycle_duration, ...
    joint_names, ...
    joint_colors, ...
    visibility, ...
    graphics_dir, ...
    quantity_name, ...
    y_label, ...
    overall_title, ...
    file_name)

    fig = figure( ...
        'Name', overall_title, ...
        'Visible', visibility, ...
        'Color', 'w', ...
        'Position', [80 60 1450 980]);

    layout = tiledlayout( ...
        fig, ...
        3, ...
        1, ...
        'TileSpacing', 'compact', ...
        'Padding', 'compact');

    for joint = 1:3
        ax = nexttile(layout);

        plot( ...
            ax, ...
            time, ...
            values(:, joint), ...
            '-', ...
            'Color', joint_colors(joint, :), ...
            'LineWidth', 2.0);

        grid(ax, 'on');
        box(ax, 'on');
        xlim(ax, [0 cycle_duration]);

        title( ...
            ax, ...
            sprintf('Joint %s Reference %s', ...
                joint_names{joint}, quantity_name), ...
            'FontName', 'Times New Roman', ...
            'FontSize', 14, ...
            'FontWeight', 'bold', ...
            'Interpreter', 'tex');

        xlabel( ...
            ax, ...
            'Time (s)', ...
            'FontName', 'Times New Roman', ...
            'FontSize', 13, ...
            'FontWeight', 'bold');

        ylabel( ...
            ax, ...
            y_label, ...
            'FontName', 'Times New Roman', ...
            'FontSize', 13, ...
            'FontWeight', 'bold');

        ax.FontName = 'Times New Roman';
        ax.FontSize = 12;
        ax.FontWeight = 'bold';
        ax.LineWidth = 1.0;
    end

    title( ...
        layout, ...
        overall_title, ...
        'FontName', 'Times New Roman', ...
        'FontSize', 17, ...
        'FontWeight', 'bold');

    exportgraphics( ...
        fig, ...
        fullfile(graphics_dir, file_name), ...
        'Resolution', 300);

    if strcmpi(visibility, 'off')
        close(fig);
    end
end
